/**
 * Overview & Purpose
 * Protects the rendered NeuroTrace shell and key interaction wiring.
 *
 * Architectural Relationships
 * Called by: Node's built-in test runner after a production build.
 * Calls: The built worker plus focused source-contract inspections.
 *
 * External Resources
 * dist/server/index.js generated by npm run build.
 *
 * Notes
 * Source assertions supplement rendering until browser-level interaction tests exist.
 */


import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(
    new Request("https://neurotrace.test/", { headers: { accept: "text/html", host: "neurotrace.test" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("renders the NeuroTrace clinical EEG workspace", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);
  const html = await response.text();
  assert.match(html, /<title>NeuroTrace — Clinical EEG Studio<\/title>/i);
  assert.match(html, /NEUROTRACE/);
  assert.match(html, /Clinical EEG Studio/);
  assert.match(html, /Context palette/);
  assert.match(html, /Clinical Observation/);
  assert.match(html, /Medication/);
  assert.match(html, />Other</);
  assert.match(html, /Label palette/);
  assert.match(html, /GPDs/);
  assert.match(html, /LPDs/);
  assert.match(html, /BIPDs/);
  assert.match(html, /GRDA/);
  assert.match(html, /LRDA/);
  assert.match(html, /N1 sleep/);
  assert.match(html, /N2 sleep/);
  assert.match(html, /N3 sleep/);
  assert.match(html, /REM sleep/);
  assert.match(html, /Load a recording to begin/);
  assert.match(html, /Open Settings/);
  assert.match(html, /og\.png/);
  assert.doesNotMatch(html, /Mark seizure|PHI stays here|Source \/ reliability|IIIC pattern|Ictal seizure|NREM sleep/);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape|react-loading-skeleton/i);
});

test("ships product source without starter preview artifacts", async () => {
  const [page, layout, packageJson] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
  ]);
  assert.match(page, /EDFSource/);
  assert.match(page, /MatSource/);
  assert.match(page, /createStoredZip/);
  assert.match(page, /aria-label="Delete annotation"/);
  assert.match(page, /aria-label="Close Settings"/);
  assert.match(page, /data-track-id=/);
  assert.match(page, /ePhys Window Labels/);
  assert.match(page, /ePhys Instance Labels/);
  assert.match(page, /context-resize-handle/);
  assert.match(page, /wave-cursor pinned/);
  assert.match(page, /Converted to a windowed duration label/);
  assert.match(page, /Context palette/);
  assert.match(page, /Entire-session context/);
  assert.match(page, /Clinical Observation/);
  assert.match(page, /Medication/);
  assert.match(page, /name:\s*"Other"/);
  assert.match(page, /candidate_events\.tsv/);
  assert.match(page, /source_content_sha256/);
  assert.match(page, /entire_session_context/);
  assert.match(page, /timed_context/);
  assert.match(page, /sha256Blob/);
  assert.match(page, /status === "committed"/);
  assert.doesNotMatch(page, /fileFingerprint/);
  assert.doesNotMatch(page, /> Cursor<\/button>|> Select<\/button>|Manage ontology/);
  assert.doesNotMatch(page, /Source \/ reliability|Candidate queue|Event labels/);
  assert.match(layout, /NeuroTrace — Clinical EEG Studio/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
  await assert.rejects(access(new URL("../app/_sites-preview", import.meta.url)));
  await access(new URL("../public/og.png", import.meta.url));
  await access(new URL(".openai/hosting.json", root));
});

test("keeps context and model-label palettes visually and semantically separate", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const sidebarStart = page.indexOf('<aside className="right-sidebar">');
  const sidebarEnd = page.indexOf("</aside>", sidebarStart);
  const sidebar = page.slice(sidebarStart, sidebarEnd);
  const contextPosition = sidebar.indexOf("Context palette");
  const labelPosition = sidebar.indexOf("Label palette");

  assert.ok(contextPosition >= 0, "context palette is rendered");
  assert.ok(labelPosition > contextPosition, "context palette is above the label palette");
  assert.match(sidebar, /compact-context-palette/);
  assert.match(sidebar, /rightContextLabels\.map/);
  assert.match(sidebar, /compact-ephys-palette/);
  assert.doesNotMatch(sidebar, /entireSessionContexts|Window context|Entire-session context/);

  const rightContextDefinition = page.match(/const rightContextLabels = \[([^\]]+)\]/)?.[1] ?? "";
  assert.match(rightContextDefinition, /"clinical"/);
  assert.match(rightContextDefinition, /"medication"/);
  assert.match(rightContextDefinition, /"note"/);
  assert.equal((rightContextDefinition.match(/"/g) ?? []).length, 6, "the right context palette has exactly three label ids");
  assert.doesNotMatch(page, /id:\s*"button"|id:\s*"asm"/, "unrequested context definitions are not shipped");

  const leftStart = page.indexOf('<section className="session-labels-section"');
  const leftEnd = page.indexOf("</section>", leftStart);
  assert.match(page.slice(leftStart, leftEnd), /entireSessionContexts\.map/, "whole-session labels are added only from the left panel");
});

test("ships a load-first state and accessible workspace dialogs", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const sourceHas = (pattern, message) => assert.ok(pattern.test(page), message);

  // The demo session may remain server-rendered, but production loading must
  // have an explicit conditional empty state instead of a synthetic fallback.
  const emptyStart = page.indexOf('<div className="recording-empty-state">');
  const emptyEnd = page.indexOf("</div>}", emptyStart);
  assert.ok(emptyStart >= 0 && emptyEnd > emptyStart, "a dedicated empty-recording surface is shipped");
  const emptyState = page.slice(emptyStart, emptyEnd);
  assert.match(emptyState, /Welcome to NeuroTrace/, "the empty state introduces the workspace before file selection");
  assert.match(emptyState, /Load (?:(?:a|an EEG) )?recording to begin/i, "the empty state has a direct load action");
  assert.match(emptyState, /EDF[\s\S]*MAT/i, "the empty state identifies supported EEG formats");
  assert.match(emptyState, /stays on this device[\s\S]*top-right for guidance/i, "the introduction points users to privacy and help information");
  assert.match(emptyState, /For help or to report bugs[\s\S]*href="mailto:alex\.maynes2001@gmail\.com"[\s\S]*alex\.maynes2001@gmail\.com/, "the introduction provides a direct support and bug-report email");
  assert.ok(emptyState.indexOf("empty-intro") < emptyState.indexOf("empty-load-prompt"), "the introduction occupies the upper section above the load prompt");
  assert.match(emptyState, /<button type="button" className="empty-load-prompt" onClick=\{\(\) => setShowImport\(true\)\}/, "only the lower load prompt opens file selection");
  assert.doesNotMatch(emptyState.slice(0, emptyState.indexOf("empty-load-prompt")), /onClick=/, "the large welcome introduction is not clickable");

  const leftStart = page.indexOf('<aside className="left-sidebar">');
  const leftEnd = page.indexOf("</aside>", leftStart);
  const leftSidebar = page.slice(leftStart, leftEnd);
  assert.doesNotMatch(leftSidebar, /compact-load-recording|>Load recording</, "the left panel never shows a duplicate recording loader");
  assert.match(leftSidebar, /\{hasRecording && <section className="recording-summary">/, "recording details appear in the left panel only after a file loads");

  sourceHas(/aria-label="Add channels"/, "CH+ has an accessible action name");
  sourceHas(/>\s*CH\+\s*<\/button>/, "the compact channel action is visible as CH+");
  sourceHas(/className=\{`channel-layout-button[\s\S]*?waveformVerticalViewport \? "↕" : "E"/, "the channel layout and vertical-reset control sits beside CH+");
  sourceHas(/aria-label="(?:Open )?Help"/, "Help trigger has an accessible name");
  sourceHas(/aria-label="(?:Open )?Settings"/, "Settings trigger has an accessible name");

  // Closed dialogs do not appear in the initial SSR response, so their
  // accessibility contract is verified directly in the conditional JSX.
  sourceHas(/aria-label="Channel controls"/, "channel dialog is named");
  sourceHas(/aria-label="Help"/, "Help dialog is named");
  sourceHas(/aria-label="Settings"/, "Settings dialog is named");
  sourceHas(/aria-modal="true"/, "workspace dialogs are exposed as modal");
});

test("keeps requested signal tools in the primary toolbar without legacy clutter", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const toolbarStart = page.indexOf('<div className="viewer-toolbar">');
  const toolbarEnd = page.indexOf('<div className="overview-block">', toolbarStart);
  assert.ok(toolbarStart >= 0 && toolbarEnd > toolbarStart, "primary viewer toolbar is present");

  const toolbar = page.slice(toolbarStart, toolbarEnd);
  for (const control of ["Spectrum", "Montage", "Filters", "Window", "Gain"]) {
    assert.match(toolbar, new RegExp(control, "i"), `${control} remains accessible from the primary toolbar`);
  }
  assert.doesNotMatch(toolbar, />\s*(?:Cursor|Select)\s*</i);
  assert.doesNotMatch(toolbar, /Mark seizure|Manage ontology/i);
  assert.match(page, /className="channel-manager-button"[\s\S]{0,160}>CH\+<\/button>/, "CH+ is in the recording rail");
  assert.match(toolbar, /className=\{`panel-bottom-button/);
  assert.match(toolbar, /aria-pressed=\{bottomTracksOpen\}/);
  assert.match(toolbar, /setBottomTracksOpen\(\(value\)\s*=>\s*!value\)/);

  const headerStart = page.indexOf('<header className="topbar">');
  const headerEnd = page.indexOf("</header>", headerStart);
  const header = page.slice(headerStart, headerEnd);
  assert.match(header, /Open Help/);
  assert.match(header, /Open Settings/);
  assert.match(header, /session-tab-strip/);

  const commandStart = page.indexOf('<footer className="command-strip">');
  const commandEnd = page.indexOf("</footer>", commandStart);
  assert.ok(commandStart >= 0 && commandEnd > commandStart, "status strip is present");
  const commandStrip = page.slice(commandStart, commandEnd);
  assert.doesNotMatch(commandStrip, /className="strip-actions"/);
  assert.doesNotMatch(commandStrip, />\s*(?:Spectrum|Controls|Settings|Help)\s*</i);
});

test("stages a unit-aware window amount until Sync applies it", async () => {
  const [page, css] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);
  assert.match(page, /type WindowTimeUnit = "ms" \| "s" \| "hr"/);
  assert.match(page, /const MIN_WINDOW_AMOUNT = \.001/);
  assert.match(page, /const MIN_TIME_WINDOW_SECONDS = MIN_WINDOW_AMOUNT \* WINDOW_UNIT_SECONDS\.ms/);
  assert.match(page, /const \[windowDraftValue, setWindowDraftValue\] = useState<string \| null>\(null\)/);

  const controlsStart = page.indexOf('<div className={`time-window-control');
  const controlsEnd = page.indexOf('<div className="gain-control"', controlsStart);
  const controls = page.slice(controlsStart, controlsEnd);
  assert.match(controls, /className="window-unit-picker"/);
  assert.match(controls, /aria-label="Cycle window time unit"[\s\S]*?onClick=\{cycleWindowDraftUnit\}/);
  assert.doesNotMatch(controls, /Previous window time unit|Next window time unit/);
  const unitPicker = controls.slice(controls.indexOf('className="window-unit-picker"'), controls.indexOf("</div>", controls.indexOf('className="window-unit-picker"')));
  assert.equal((unitPicker.match(/<button/g) ?? []).length, 1, "the unit has one change button beneath it");
  assert.match(controls, /min=\{windowDraftMinimum\}/);
  assert.match(controls, /max=\{windowDraftMaximum\}/);
  assert.match(controls, /onChange=\{\(event\) => setWindowDraftValue\(event\.target\.value\)\}/);
  assert.doesNotMatch(controls, /onChange=\{[^}]*setTimeWindow/, "editing the staged amount does not reload the waveform");
  assert.match(controls, /aria-label="Decrease window amount"[\s\S]*?adjustWindowDraft\(-1\)/);
  assert.match(controls, /aria-label="Increase window amount"[\s\S]*?adjustWindowDraft\(1\)/);
  assert.doesNotMatch(controls, /zoomTimeWindow\(/, "the amount buttons stage numeric changes instead of immediately zooming");
  assert.match(controls, /className="window-sync-button"/);
  assert.match(controls, /onClick=\{syncWindowDraft\}/);
  assert.match(controls, /className="window-sync-button"[\s\S]*?<span aria-hidden="true">✓<\/span><\/button>/);
  assert.doesNotMatch(controls, />Sync</, "the icon-only Sync button does not repeat its accessible name visually");
  assert.match(controls, /className="window-amount-field"[\s\S]*?className="window-unit-picker"[\s\S]*?className="window-step-buttons"[\s\S]*?aria-label="Increase window amount"[\s\S]*?aria-label="Decrease window amount"[\s\S]*?className="window-sync-button"/, "the amount, unit, vertical plus/minus controls, and Sync action appear in that order");

  const gainStart = page.indexOf('<div className="gain-control"', controlsEnd);
  const gainEnd = page.indexOf('<div className="toolbar-spacer"', gainStart);
  const gainControls = page.slice(gainStart, gainEnd);
  assert.match(gainControls, /<b>\{gain\.toFixed\(1\)\}×<\/b>[\s\S]*?className="gain-step-buttons"[\s\S]*?aria-label="Increase gain"[\s\S]*?aria-label="Decrease gain"/, "gain plus/minus controls are stacked to the right of its value");

  const windowLogic = page.slice(page.indexOf("const setTimeWindow"), page.indexOf("const commitMutation"));
  assert.match(windowLogic, /maximumWindow = Math\.max\(Number\.EPSILON, meta\.durationSec\)/);
  assert.doesNotMatch(windowLogic, /Math\.min\(300/, "the full recording duration is accepted");
  assert.match(windowLogic, /numericValue \* windowUnitSeconds/);
  assert.match(windowLogic, /currentValue \+ direction \* step/);
  assert.match(windowLogic, /setTimeWindow\(nextWindow\)/);
  assert.match(windowLogic, /setWindowDraftValue\(null\)/);
  assert.match(css, /\.window-unit-picker\s*\{/);
  assert.match(css, /\.window-unit-picker\s*\{[^}]*flex-direction:\s*column/);
  assert.match(css, /\.time-window-control\.pending\s*\{/);
  assert.match(css, /\.window-sync-button\s*\{[^}]*width:\s*18px[^}]*height:\s*21px/s);
  assert.match(css, /\.window-step-buttons\s*\{[^}]*display:\s*flex[^}]*flex-direction:\s*column/);
  assert.match(css, /\.gain-step-buttons\s*\{[^}]*display:\s*flex[^}]*flex-direction:\s*column/);
});

test("visually subdues controls that are temporarily unavailable", async () => {
  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  assert.match(css, /:where\(button, input, select, textarea\):disabled\s*\{[^}]*filter:\s*brightness\(\.58\) saturate\(\.3\)[^}]*box-shadow:\s*none !important/s);
  assert.match(css, /\.legacy-event-picker:disabled\s*\{\s*opacity:\s*\.38/);
});

test("keeps footer status text separated from annotation actions", async () => {
  const [page, css] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);
  const footerStart = page.indexOf('<footer className="command-strip">');
  const footerEnd = page.indexOf("</footer>", footerStart);
  const footer = page.slice(footerStart, footerEnd);

  assert.match(footer, /className="command-status-text">\{toast\}/);
  assert.match(footer, /className="annotation-command-actions"/);
  assert.match(css, /\.command-status-text\s*\{[^}]*min-width:\s*0[^}]*overflow:\s*hidden[^}]*text-overflow:\s*ellipsis/);
  assert.match(css, /\.annotation-command-actions\s*\{[^}]*padding-left:\s*12px[^}]*border-left:/);
});

test("resolves palette clicks from session, selection, or pinned-cursor context", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const resolverStart = page.indexOf("const placePaletteLabel");
  const resolverEnd = page.indexOf("const updateAnnotation", resolverStart);
  assert.ok(resolverStart >= 0 && resolverEnd > resolverStart, "palette placement resolver is present");

  const resolver = page.slice(resolverStart, resolverEnd);
  assert.match(resolver, /label\.geometry\s*!==\s*"session"/);
  assert.match(resolver, /cursorLocked/);
  assert.match(resolver, /selection\?\.start\s*\?\?\s*cursorTime/);
  assert.match(resolver, /selection\?\.end/);
  assert.match(resolver, /label\.category\s*===\s*"Context"[\s\S]*?"context-window"[\s\S]*?"context-instance"/);
  assert.match(resolver, /selection[\s\S]*?\?\s*"windowed"[\s\S]*?:\s*"instance"/);
  assert.match(resolver, /addAnnotation\(label,\s*selection\?\.start\s*\?\?\s*cursorTime,\s*selection\?\.end,\s*intent\)/);

  const addStart = page.indexOf("const addAnnotation");
  const addEnd = page.indexOf("const placePaletteLabel", addStart);
  const addAnnotation = page.slice(addStart, addEnd);
  assert.match(addAnnotation, /intent\s*===\s*"instance"\s*\|\|\s*intent\s*===\s*"context-instance"[\s\S]*?\?\s*"point"/);
  assert.match(addAnnotation, /intent\s*===\s*"windowed"\s*\|\|\s*intent\s*===\s*"context-window"[\s\S]*?\?\s*"interval"/);
  assert.match(addAnnotation, /intent\s*===\s*"context-instance"\s*\|\|\s*intent\s*===\s*"context-window"[\s\S]*?\?\s*"context"/);
  assert.match(addAnnotation, /intent\s*===\s*"instance"[\s\S]*?\?\s*"instance"/);
  assert.match(addAnnotation, /intent\s*===\s*"windowed"[\s\S]*?\?\s*"windowed"/);

  const paletteClickBindings = page.match(/onClick=\{\(\) => placePaletteLabel\(label\)\}/g) ?? [];
  assert.ok(paletteClickBindings.length >= 2, "both context and label palettes use the same placement resolver");

  const dropStart = page.indexOf("const onLabelDrop");
  const dropEnd = page.indexOf("const onLabelDragOver", dropStart);
  const drop = page.slice(dropStart, dropEnd);
  assert.match(drop, /label\.category\s*===\s*"Context"[\s\S]*?"context-window"[\s\S]*?"context-instance"/);
  assert.match(drop, /selection\s*\?\s*"windowed"\s*:\s*"instance"/);
  assert.match(drop, /selection\?\.start\s*\?\?\s*time/);
  assert.match(drop, /selection\?\.end/);

  const pointerUpStart = page.indexOf("const onWavePointerUp");
  const pointerUpEnd = page.indexOf("const onLabelDrop", pointerUpStart);
  assert.match(page.slice(pointerUpStart, pointerUpEnd), /pointer\.moved\s*&&\s*Math\.abs\(time - pointer\.startTime\)\s*>\s*0/);
});

test("renders accessible session tabs and isolates each session workspace", async () => {
  const response = await render();
  const html = await response.text();
  assert.match(html, /role="tablist"[^>]*aria-label="EEG sessions"/);
  assert.match(html, /role="tab"[^>]*aria-selected="true"/);
  assert.match(html, /aria-label="Add blank session"/);
  assert.match(html, /Load a recording to begin/);
  assert.doesNotMatch(html, /P-1027|UNM_EMU/);

  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const storeStart = page.indexOf("const storeActiveSession");
  const storeEnd = page.indexOf("const applySessionSnapshot", storeStart);
  const store = page.slice(storeStart, storeEnd);
  assert.match(store, /sessionSnapshotsRef\.current\.set\(activeSessionId/);
  for (const state of ["hasRecording", "source", "annotations", "candidates", "selectedChannels", "badChannels", "viewStart", "timebase", "undo", "redo"]) {
    assert.match(store, new RegExp(`\\b${state}\\b`), `${state} is retained per session`);
  }

  const switchStart = page.indexOf("const switchSession");
  const switchEnd = page.indexOf("const createBlankSession", switchStart);
  const switchSession = page.slice(switchStart, switchEnd);
  assert.ok(
    switchSession.indexOf("storeActiveSession()") < switchSession.indexOf("applySessionSnapshot(snapshot)"),
    "the outgoing workspace is saved before the target workspace is restored",
  );

  const blankSnapshotStart = page.indexOf("function blankSessionSnapshot");
  const blankSnapshotEnd = page.indexOf("function primarySampleRate", blankSnapshotStart);
  const blankSnapshot = page.slice(blankSnapshotStart, blankSnapshotEnd);
  assert.match(blankSnapshot, /hasRecording:\s*false/);
  assert.match(blankSnapshot, /annotations:\s*\[\]/);
  assert.match(blankSnapshot, /candidates:\s*\[\]/);
  assert.match(blankSnapshot, /selectedChannels:\s*\[\]/);
  assert.match(blankSnapshot, /cursorLocked:\s*false/);

  const blankStart = page.indexOf("const createBlankSession");
  const blankEnd = page.indexOf("const closeSession", blankStart);
  const blank = page.slice(blankStart, blankEnd);
  assert.match(blank, /blankSessionSnapshot\(demoSource,\s*id\)/);
  assert.match(blank, /sessionSnapshotsRef\.current\.set\(id,\s*snapshot\)/);
  assert.match(blank, /setSessionTabs\(\(current\)\s*=>\s*\[\.\.\.current/);

  const loadStart = page.indexOf("const loadSource");
  const loadEnd = page.indexOf("const confirmDatImport", loadStart);
  const load = page.slice(loadStart, loadEnd);
  assert.match(load, /setHasRecording\(true\)/);
  assert.match(load, /const targetSessionId\s*=\s*activeSessionId/);
  assert.match(load, /tab\.id\s*===\s*targetSessionId/);
  assert.match(load, /title:\s*shortFileName/);
  const previewIndex = load.indexOf("sourceRef.current = source");
  const verificationIndex = load.indexOf("await buildEDFEnvelopeWindowOffThread");
  assert.ok(previewIndex >= 0 && verificationIndex > previewIndex, "a read-only waveform preview opens before full source verification finishes");
  assert.match(load, /sourceVerificationRef\.current\s*=\s*true/);
  assert.match(load, /buildEDFEnvelopeWindowOffThread[\s\S]*?integrity:\s*\{\s*sha256:\s*true,\s*edfAnnotations:\s*true\s*\}/);
  assert.match(load, /buildRawDatEnvelopeWindowOffThread[\s\S]*?integrity:\s*\{\s*sha256:\s*true\s*\}/);
  assert.match(load, /signal:\s*verificationAbortController\.signal/);
  assert.ok(load.indexOf("setSourceHash(interpretationHash)") > verificationIndex, "verified source identity attaches only after the worker completes");
  assert.ok(load.indexOf("setSessionTabs((current)") > verificationIndex, "tab identity is not replaced until verification succeeds");
  assert.match(load, /activeSessionIdRef\.current\s*!==\s*targetSessionId/);
  assert.match(load, /duplicateEntry[\s\S]*?applySessionSnapshot\(duplicateSnapshot\)[\s\S]*?return false/);

  const closeStart = page.indexOf("const closeSession");
  const closeEnd = page.indexOf("const updateControlBinding", closeStart);
  const close = page.slice(closeStart, closeEnd);
  assert.match(close, /storeActiveSession\(\)/);
  assert.match(close, /recoveryStatus\s*===\s*"error"/);
  assert.match(close, /export it before closing/i);
  assert.match(close, /remaining\.length\s*===\s*0/);
  assert.match(close, /blankSessionSnapshot\(demoSource,\s*replacementId\)/);
  assert.doesNotMatch(close, /sessionTabs\.length\s*<=\s*1/);
  assert.match(page, /className="session-tab-close"/);
  assert.doesNotMatch(page, /disabled=\{importBusy\s*\|\|\s*sessionTabs\.length\s*<=\s*1\}/);
  assert.match(page, /window\.addEventListener\("pagehide",\s*flush\)/);

  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const closeStylesStart = styles.indexOf(".session-tab-close {");
  const closeStylesEnd = styles.indexOf(".add-session-tab", closeStylesStart);
  const closeStyles = styles.slice(closeStylesStart, closeStylesEnd);
  assert.match(closeStyles, /right:\s*7px/);
  assert.doesNotMatch(closeStyles, /opacity:\s*0/);

  const importStart = page.indexOf("const importFiles");
  const importEnd = page.indexOf("const confirmDatImport", importStart);
  assert.match(page.slice(importStart, importEnd), /importBusyRef\.current/);
  assert.match(page, /!importBusyRef\.current\s*&&\s*event\.dataTransfer\.files\.length/);
});

test("shows actionable upload errors for unsupported, incomplete, or mismatched recordings", async () => {
  const [page, styles] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);

  const validationStart = page.indexOf("function validateUploadSelection");
  const validationEnd = page.indexOf("function uploadErrorFrom", validationStart);
  const validation = page.slice(validationStart, validationEnd);
  assert.match(validation, /Unsupported file type/);
  assert.match(validation, /file\.size\s*===\s*0/);
  assert.match(validation, /file\.size\s*<\s*256/);
  assert.match(validation, /file\.size\s*<\s*128/);
  assert.match(validation, /file\.size\s*%\s*2\s*!==\s*0/);
  assert.match(validation, /MAT and DAT files do not match/);

  const importStart = page.indexOf("const importFiles");
  const importEnd = page.indexOf("const confirmDatImport", importStart);
  const importer = page.slice(importStart, importEnd);
  assert.match(importer, /validateUploadSelection\(files\)/);
  assert.match(importer, /setUploadError\(uploadFailure\)/);
  assert.match(importer, /setShowImport\(true\)/, "a parser failure reopens the dialog so its error remains visible");

  const modalStart = page.indexOf("{showImport &&");
  const modalEnd = page.indexOf("{confirmCommit.length", modalStart);
  const modal = page.slice(modalStart, modalEnd);
  assert.match(modal, /className="upload-error"[^>]*role="alert"/);
  assert.match(modal, /aria-live="assertive"/);
  assert.match(modal, /uploadError\.files\.join/);
  assert.match(modal, /aria-label="Dismiss upload error"/);
  assert.match(modal, /event\.target\.value\s*=\s*""/, "the same corrected or recopied file can be selected again");
  assert.match(styles, /\.drop-zone\.has-error\s*\{/);
  assert.match(styles, /\.upload-error\s*\{/);
});

test("toggles each loaded tab between the recording and file structure analysis", async () => {
  const [page, styles] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);

  assert.match(page, /contentView:\s*"recording"\s*\|\s*"structure"/);
  const tabShellStart = page.indexOf('<div className="session-tabs">');
  const tabShellEnd = page.indexOf("</nav>", tabShellStart);
  const tabs = page.slice(tabShellStart, tabShellEnd);
  const structureButton = tabs.indexOf("session-tab-structure");
  const closeButton = tabs.indexOf("session-tab-close");
  assert.ok(structureButton >= 0 && structureButton < closeButton, "the structure toggle sits immediately left of the tab close button");
  assert.match(tabs, /disabled=\{importBusy \|\| !tabHasRecording\}/);
  assert.match(tabs, /aria-pressed=\{tab\.contentView === "structure"\}/);

  const toggleStart = page.indexOf("const toggleSessionContentView");
  const toggleEnd = page.indexOf("const updateControlBinding", toggleStart);
  const toggle = page.slice(toggleStart, toggleEnd);
  assert.match(toggle, /if \(id !== activeSessionId\) switchSession\(id\)/, "using the control on an inactive tab opens that tab");
  assert.match(toggle, /contentView:\s*nextView/);
  assert.match(toggle, /setPlaying\(false\)/);

  assert.match(page, /activeSessionContentView === "structure" && hasRecording \? <FileStructurePanel/);
  assert.equal(
    page.match(/\[activeSessionContentView, hasRecording\]/g)?.length,
    3,
    "returning to the recording remounts canvas measurement, frame diagnostics, and wheel controls",
  );
  assert.match(page, /\[activeCandidateTime, activeSessionContentView,[^\]]+\]/, "returning to the recording redraws the waveform canvas");
  assert.match(page, /\[activeSessionContentView, expandedChannels\]/, "returning to the recording restores channel viewport measurement");
  const panelStart = page.indexOf("function FileStructurePanel");
  const panelEnd = page.indexOf("function GeneralInfoPanel", panelStart);
  const panel = page.slice(panelStart, panelEnd);
  for (const content of ["How the file is organized", "File information", "Channel information", "Warnings and assumptions"]) {
    assert.match(panel, new RegExp(content));
  }
  assert.match(panel, /meta\.channelLabels\.map/);
  assert.match(panel, /Filter file channels/);
  assert.match(page, /meta\.format === "edf" \|\| meta\.format === "edf\+"/);
  assert.match(page, /meta\.format === "mat-v5"/);
  assert.match(page, /meta\.format === "raw-int16-le"/);

  const structureRule = styles.match(/\.session-tab-structure\s*\{([^}]+)\}/)?.[1] ?? "";
  const closeRule = styles.match(/\.session-tab-close\s*\{([^}]+)\}/)?.[1] ?? "";
  assert.match(structureRule, /right:\s*31px/);
  assert.match(closeRule, /right:\s*7px/);
  assert.match(styles, /\.file-structure-panel\s*\{/);
  assert.match(styles, /\.file-channel-table\s*\{/);
});

test("wires channel, Help, and Settings dialogs to operable controls", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");

  const channelsStart = page.indexOf("{showChannels &&");
  const channelsEnd = page.indexOf("{showHelp &&", channelsStart);
  const channels = page.slice(channelsStart, channelsEnd);
  assert.match(channels, /role="dialog"[^>]*aria-modal="true"[^>]*aria-label="Channel controls"/);
  assert.match(channels, /aria-label="Close channel controls"/);
  assert.match(channels, /setShowChannels\(false\)/);
  assert.match(channels, /aria-label="Search detected channels"/);
  assert.match(channels, />Enable all<\/button>/);
  assert.match(channels, />Disable all<\/button>/);
  assert.match(channels, /checked=\{selectedChannels\.has\(index\)\}/);
  assert.match(channels, /if\s*\(next\.has\(index\)\)\s*next\.delete\(index\)/);
  assert.match(channels, /setBadChannels/);
  assert.match(channels, /source channel \{index \+ 1\}/);
  assert.match(channels, /original channel provenance/i);

  const helpStart = page.indexOf("{showHelp &&");
  const helpEnd = page.indexOf("{showSettings &&", helpStart);
  const help = page.slice(helpStart, helpEnd);
  assert.match(help, /role="dialog"[^>]*aria-modal="true"[^>]*aria-label="Help"/);
  assert.match(help, /aria-label="Close Help"/);
  assert.match(help, /Session tabs/);
  assert.match(help, /Waveform labeling/);
  assert.match(help, /CH\+ channel manager/);

  const settingsStart = page.indexOf("{showSettings &&");
  const settingsEnd = page.indexOf("{showSessionMap &&", settingsStart);
  const settings = page.slice(settingsStart, settingsEnd);
  assert.match(settings, /role="dialog"[^>]*aria-modal="true"[^>]*aria-label="Settings"/);
  assert.match(settings, /aria-label="Close Settings"/);
  assert.match(settings, /Restore defaults/);
  assert.match(settings, /controlBindings\[row\.key\]/);
  assert.match(settings, /setControlBindings/);
  assert.match(settings, /updateControlBinding/);
  assert.match(settings, /swaps the two actions/);
  assert.match(settings, /Label snapping/);

  const keyboardStart = page.indexOf("const modalOpen");
  const keyboardEnd = page.indexOf('window.addEventListener("keydown"', keyboardStart);
  const keyboard = page.slice(keyboardStart, keyboardEnd);
  for (const dialog of ["showHelp", "showSettings", "showChannels"]) {
    assert.match(keyboard, new RegExp(`\\b${dialog}\\b`), `${dialog} participates in Escape handling`);
  }
  assert.match(keyboard, /event\.key\s*===\s*"Escape"/);
  assert.match(page, /setAttribute\("inert"/);
  assert.match(page, /event\.key\s*!==\s*"Tab"/);
  assert.match(page, /modalOpen\s*&&\s*zoomModifier/);
});

test("reattaches non-passive waveform wheel controls after a blank session loads", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");

  const wheelHandlerStart = page.indexOf("const onViewerWheel");
  const wheelHandlerEnd = page.indexOf("useLayoutEffect", wheelHandlerStart);
  assert.ok(wheelHandlerStart >= 0 && wheelHandlerEnd > wheelHandlerStart, "the waveform wheel handler is present");
  const wheelHandler = page.slice(wheelHandlerStart, wheelHandlerEnd);
  assert.match(wheelHandler, /event\.preventDefault\(\)/, "browser page zoom and scrolling are intercepted over the recording");
  assert.match(wheelHandler, /event\.ctrlKey\s*\|\|\s*event\.metaKey/, "trackpad pinch and modified wheel gestures enter time zoom");
  assert.match(wheelHandler, /zoomWheelFrameRef[\s\S]*?requestAnimationFrame[\s\S]*?setTimeWindow\(/, "pinch zoom is coalesced to one EEG time-window update per frame");
  assert.match(wheelHandler, /event\.deltaX/);
  assert.match(wheelHandler, /event\.deltaY/);
  assert.match(wheelHandler, /overExpandedChannels[\s\S]*?Math\.abs\(event\.deltaY\)\s*>\s*Math\.abs\(event\.deltaX\)[\s\S]*?return/, "vertical gestures scroll expanded channels natively");
  assert.match(wheelHandler, /previewViewStartSafe\(/, "ordinary wheel and trackpad gestures pan the recording without starting a read");
  assert.match(wheelHandler, /window\.setTimeout[\s\S]*?setSignalViewStart\(wheelPanTargetRef\.current\)[\s\S]*?WHEEL_PAN_SETTLE_MS/, "signal loading starts only after panning settles");

  const listenerStart = page.indexOf('viewer.addEventListener("wheel"');
  const listenerEffectStart = page.lastIndexOf("useEffect(() => {", listenerStart);
  const listenerEffectEnd = page.indexOf("const selectCandidate", listenerStart);
  assert.ok(listenerEffectStart >= 0 && listenerEffectEnd > listenerStart, "the wheel listener lifecycle is present");
  const listenerEffect = page.slice(listenerEffectStart, listenerEffectEnd);
  assert.match(listenerEffect, /viewerRef\.current/);
  assert.match(listenerEffect, /passive:\s*false/, "wheel handling can prevent browser-level zoom");
  assert.match(listenerEffect, /removeEventListener\("wheel"/, "the wheel listener is cleaned up");
  assert.match(
    listenerEffect,
    /\},\s*\[[^\]]*\bhasRecording\b[^\]]*\]\);/,
    "the listener effect reruns when a recording replaces the initial blank state",
  );
});

test("resizes context from its top edge, with upward drag expanding the track", async () => {
  const [page, css] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);

  const resizeRead = page.indexOf("const resize = contextResizeRef.current");
  const resizeEffectStart = page.lastIndexOf("useEffect(() => {", resizeRead);
  const resizeEffectEnd = page.indexOf("const jumpTo", resizeRead);
  assert.ok(resizeEffectStart >= 0 && resizeEffectEnd > resizeRead, "the context resize lifecycle is present");
  const resizeEffect = page.slice(resizeEffectStart, resizeEffectEnd);
  assert.match(
    resizeEffect,
    /resize\.startHeight\s*-\s*\(\s*event\.clientY\s*-\s*resize\.startY\s*\)/,
    "dragging upward increases context height and dragging downward decreases it",
  );

  const handleRule = css.match(/\.context-resize-handle\s*\{([^}]+)\}/)?.[1] ?? "";
  assert.match(handleRule, /\btop\s*:/, "the resize affordance is attached to the context track's top edge");
  assert.doesNotMatch(handleRule, /\bbottom\s*:/, "the old bottom-edge resize affordance is removed");
});

test("resizes the spectrogram vertically from its top edge", async () => {
  const [page, css] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);

  const spectrumStart = page.indexOf("function SpectrogramPanel");
  const spectrumEnd = page.indexOf("type FileStructureNode", spectrumStart);
  assert.ok(spectrumStart >= 0 && spectrumEnd > spectrumStart, "the spectrogram panel implementation is present");
  const spectrum = page.slice(spectrumStart, spectrumEnd);
  assert.match(spectrum, /const \[spectrogramHeight,\s*setSpectrogramHeight\]\s*=\s*useState\(DEFAULT_SPECTROGRAM_HEIGHT\)/);
  assert.match(spectrum, /resize\.startHeight\s*-\s*\(event\.clientY\s*-\s*resize\.startY\)/, "dragging upward increases spectrogram height");
  assert.match(spectrum, /className="spectrogram-resize-handle"[\s\S]*?role="separator"[\s\S]*?aria-valuenow=/);
  assert.match(spectrum, /style=\{\{ height:\s*spectrogramHeight \}\}/);

  const handleRule = css.match(/\.spectrogram-resize-handle\s*\{([^}]+)\}/)?.[1] ?? "";
  assert.match(handleRule, /\btop\s*:/, "the resize affordance is attached to the spectrogram's top edge");
  assert.match(handleRule, /cursor:\s*ns-resize/);
  assert.match(handleRule, /touch-action:\s*none/);
});

test("keeps the right panel label view ordered like the ontology palette", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const sidebarStart = page.indexOf('<aside className="right-sidebar">');
  const sidebarEnd = page.indexOf("</aside>", sidebarStart);
  assert.ok(sidebarStart >= 0 && sidebarEnd > sidebarStart, "the right label panel is present");
  const sidebar = page.slice(sidebarStart, sidebarEnd);

  const switchPosition = sidebar.indexOf("right-panel-mode-switch");
  const searchPosition = sidebar.search(/Search ontology/i);
  const contextPosition = sidebar.indexOf("Context Labels");
  const ephysPosition = sidebar.indexOf("ePhys Labels");
  assert.ok(switchPosition >= 0, "the panel mode switch is available at the top of the right panel");
  assert.ok(searchPosition > switchPosition, "ontology search follows the panel mode switch");
  assert.ok(searchPosition >= 0, "ontology search is available at the top of the right panel");
  assert.ok(contextPosition > searchPosition, "context labels follow ontology search");
  assert.ok(ephysPosition > contextPosition, "ePhys labels follow context labels");
  assert.doesNotMatch(sidebar, /<QcPanel|\bQC\b/, "QC does not compete with the label palette");
});

test("switches waveform dragging between labeling selection and two-dimensional general-info zoom", async () => {
  const [page, css] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);

  assert.match(page, /useState<"labels" \| "inspect" \| "resources">\("labels"\)/);
  assert.match(page, /className="right-panel-mode-switch" role="tablist" aria-label="Right panel tools"/);
  assert.match(page, /role="tab"[^>]*>[\s\S]{0,80}Labeling tools/);
  assert.match(page, /role="tab"[^>]*>[\s\S]{0,80}General info/);
  assert.match(page, /rightPanelView === "inspect" \? <GeneralInfoPanel/);

  const pointerStart = page.indexOf("const onWavePointerDown");
  const pointerEnd = page.indexOf("const onLabelDrop", pointerStart);
  const pointerHandlers = page.slice(pointerStart, pointerEnd);
  assert.match(pointerHandlers, /inspectionBox: inspectionMode && pointerRef\.current\.moved/);
  assert.match(pointerHandlers, /if \(pending\.inspectionBox\) setInspectionRange\(pending\.inspectionBox\)/);
  assert.match(pointerHandlers, /zoomToTimeRange\(range\.start, range\.end\)/);
  assert.match(pointerHandlers, /fitWaveformVerticallyToInspectionBox\(range, rect\)/);
  assert.match(page, /composeVerticalViewport\(expandedChannels \? null : current, selection\)/);
  assert.match(page, /expandedChannels[\s\S]*?channelRowLayout\.totalUnits \* 60/, "expanded, scrolled channels use content-space box bounds");
  assert.doesNotMatch(pointerHandlers, /setInspectionRowRange|setSelectedChannels/, "box zoom preserves every enabled channel");
  assert.match(pointerHandlers, /setSelection\(\{ start: Math\.min\(pointer\.startTime, time\), end: Math\.max\(pointer\.startTime, time\) \}\)/);
  assert.match(pointerHandlers, /choose a label/);

  assert.match(page, /className=\{`canvas-shell \$\{inspectionMode \? "inspection-mode" : ""\}`\}/);
  assert.match(page, /className="wave-inspection-range"/);
  assert.match(page, /top: `\$\{inspectionRange\.top \* 100\}%`/);
  assert.match(page, /height: `\$\{Math\.max\(0, inspectionRange\.bottom - inspectionRange\.top\) \* 100\}%`/);
  assert.match(page, /Drag a box to fit that exact time and channel area to the full waveform view\. All channels stay enabled\./);
  assert.doesNotMatch(page, /applyDisplayRowRange|inspectionRowRange/, "box zoom does not remove unboxed channels");
  assert.match(page, /const rowStyle = channelRailRowStyle\(index\)/);
  assert.match(page, /unprojectVerticalFraction\(screenFraction, waveformVerticalViewport\)/);
  assert.match(page, /const selected = channel === focusedChannel/);
  assert.doesNotMatch(
    page,
    /\[activeCandidateTime, activeSessionContentView,[^\]]*inspection(?:Dragging|Range)/,
    "the DOM inspection rectangle updates without retracing busy waveform paths",
  );
  assert.match(page, /const focused = !inspectionDragging && !inspectionRange\?\.dragged && focusedChannel === index/);
  assert.doesNotMatch(page, /inspectionHighlighted|inspection-highlighted/);
  assert.match(css, /\.right-panel-mode-switch\s*\{/);
  assert.match(css, /\.canvas-shell canvas\s*\{[^}]*cursor:\s*crosshair/);
  assert.doesNotMatch(css, /cursor:\s*zoom-in/, "General Info keeps the normal waveform crosshair");
  assert.match(css, /\.wave-inspection-range\s*\{[^}]*min-height:\s*12px/);
  assert.match(css, /\.channel-rail\.viewport-zoomed\s*\{[^}]*overflow:\s*hidden/);
  assert.doesNotMatch(css, /\.wave-inspection-range\s*\{[^}]*(?:top:\s*0|bottom:\s*0)/);
  assert.match(css, /\.general-info-panel\s*\{/);
});

test("toggles live resource usage from the control left of Help and Settings", async () => {
  const [page, css] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);

  assert.match(page, /const \[rightPanelView,\s*setRightPanelView\]\s*=\s*useState<"labels" \| "inspect" \| "resources">\("labels"\)/);
  const actionsStart = page.indexOf('<div className="top-actions utility-actions">');
  const actionsEnd = page.indexOf("</div>", actionsStart);
  const actions = page.slice(actionsStart, actionsEnd);
  const resourcePosition = actions.indexOf("Show resource usage");
  const helpPosition = actions.indexOf("Open Help");
  const settingsPosition = actions.indexOf("Open Settings");
  assert.ok(resourcePosition >= 0, "the resource control is present in the top-right utility group");
  assert.ok(resourcePosition < helpPosition && helpPosition < settingsPosition, "resource usage sits immediately before Help and Settings");
  assert.match(actions, /setRightPanelView\("resources"\)[\s\S]*?setRightPanelOpen\(true\)/);

  const sidebarStart = page.indexOf('<aside className="right-sidebar">');
  const sidebarEnd = page.indexOf("</aside>", sidebarStart);
  const sidebar = page.slice(sidebarStart, sidebarEnd);
  assert.match(sidebar, /rightPanelView\s*===\s*"resources"\s*\?\s*<ResourceUsagePanel/);

  const resourcePanelStart = page.indexOf("function ResourceUsagePanel");
  const resourcePanelEnd = page.indexOf("function QcPanel", resourcePanelStart);
  const resourcePanel = page.slice(resourcePanelStart, resourcePanelEnd);
  assert.match(resourcePanel, /performance as PerformanceWithMemory/);
  assert.match(resourcePanel, /navigator\.storage/);
  assert.match(resourcePanel, /Signal cache/);
  assert.match(resourcePanel, /Total source bytes read/);
  assert.match(resourcePanel, /browser file boundary/);
  assert.match(resourcePanel, /Main-thread pressure/);
  assert.match(resourcePanel, /Process CPU utilization/);
  assert.match(resourcePanel, /Transient buffers processed/);
  assert.match(resourcePanel, /Garbage collection/);
  assert.match(resourcePanel, /Canvas backing store/);
  assert.match(resourcePanel, /GPU\/compositor surfaces/);
  assert.match(resourcePanel, /Dropped frames/);
  assert.match(resourcePanel, /UI frame cadence/);
  assert.match(resourcePanel, /Active retained view/);
  assert.match(resourcePanel, /Reading from/);
  assert.match(resourcePanel, /Recording data is not uploaded/);
  assert.match(resourcePanel, /Browsers expose the file name, not its full local path/);
  assert.match(css, /\.resource-panel\s*\{/);
  assert.match(css, /\.resource-glyph\s*\{/);
});

test("moves QC into an accessible tab inside the Session Map dialog", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const sessionMapStart = page.indexOf("function SessionMap(");
  assert.ok(sessionMapStart >= 0, "SessionMap is present");
  const sessionMap = page.slice(sessionMapStart);

  assert.match(sessionMap, /role="tablist"/, "Session Map exposes its view switcher as a tab list");
  assert.match(sessionMap, /role="tab"[\s\S]{0,300}Session map/i, "the map remains the primary tab");
  assert.match(sessionMap, /role="tab"[\s\S]{0,300}>QC(?:\s|<)/i, "QC is available as a sibling tab");
  assert.match(sessionMap, /<QcPanel\b/, "the existing QC report renders inside Session Map");

  const invocationStart = page.indexOf("{showSessionMap && <SessionMap");
  const invocationEnd = page.indexOf("/>}", invocationStart);
  assert.ok(invocationStart >= 0 && invocationEnd > invocationStart, "the Session Map dialog is wired from the workspace");
  const invocation = page.slice(invocationStart, invocationEnd);
  assert.match(invocation, /(?:issues|qcIssues)=\{qcIssues\}/, "QC findings are passed into Session Map");
  assert.match(invocation, /badChannels=\{badChannels\}/);
  assert.match(invocation, /recoveryStatus=\{recoveryStatus\}/);
});

test("opens patient information as a modal instead of expanding the left panel", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const leftStart = page.indexOf('<aside className="left-sidebar">');
  const leftEnd = page.indexOf("</aside>", leftStart);
  const left = page.slice(leftStart, leftEnd);
  assert.match(left, /setShowPatientInfo\(true\)/);
  assert.doesNotMatch(left, /patient-info-panel|aria-expanded|patientInfoOpen/);
  assert.ok(
    left.indexOf('className="patient-info-disclosure"') < left.indexOf('className="session-map-row"'),
    "Patient Info appears above Session Map",
  );

  const modalStart = page.indexOf("{showPatientInfo && hasRecording");
  const modalEnd = page.indexOf("{showAnnotationEditor", modalStart);
  assert.ok(modalStart >= 0 && modalEnd > modalStart, "patient information popup is present");
  const modal = page.slice(modalStart, modalEnd);
  assert.match(modal, /role="dialog"[^>]*aria-modal="true"[^>]*aria-label="Patient information"/);
  assert.match(modal, /Close patient information/);
  assert.match(modal, /Patient Information/);
  assert.match(modal, /Replace recording/);
  assert.match(modal, /Export model-ready bundle/);
});

test("starts with a compact Session Labels area and resizes it against Instance Queue", async () => {
  const [page, css] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);
  assert.match(page, /const \[sessionLabelsHeight,\s*setSessionLabelsHeight\]\s*=\s*useState\(145\)/);
  assert.match(page, /className="session-labels-section"[^>]*ref=\{sessionLabelsSectionRef\}[^>]*height:\s*sessionLabelsHeight/);
  assert.match(page, /className="left-split-resize-handle"/);
  assert.match(page, /Resize Session Labels and Instance Queue/);
  assert.match(page, /availableHeight:\s*sessionHeight\s*\+\s*queueHeight/);
  assert.match(page, /resize\.startHeight\s*\+\s*\(event\.clientY\s*-\s*resize\.startY\)/);
  assert.match(page, /ref=\{queueSectionRef\}/);
  assert.match(page, /ArrowUp/);
  assert.match(page, /ArrowDown/);
  assert.match(css, /\.left-sidebar \.session-labels-section\s*\{[^}]*flex:\s*0 0 auto;[^}]*min-height:\s*105px;/);
  assert.match(css, /\.left-split-resize-handle\s*\{[^}]*height:\s*9px;[^}]*cursor:\s*ns-resize;/);
});

test("uses Instance Queue only to navigate file events, instance labels, and non-session context", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const entriesStart = page.indexOf("const instanceQueueEntries");
  const entriesEnd = page.indexOf("const activeQueueIndex", entriesStart);
  const entries = page.slice(entriesStart, entriesEnd);
  assert.match(entries, /item\.track\s*===\s*"instance"/);
  assert.match(entries, /item\.track\s*===\s*"context"/);
  assert.match(entries, /annotationGeometry\(item\)\s*!==\s*"session"/);
  assert.match(entries, /candidates/);
  assert.doesNotMatch(entries, /linkedCandidateIds/, "a source event stays navigable while its linked ictal interval is still a draft");
  assert.match(entries, /confidence:\s*Math\.round\(clamp\(item\.confidence,\s*0,\s*100\)\)/);
  assert.match(entries, /confidence:\s*item\.confidence/, "file-event confidence remains editable and persisted");
  assert.match(entries, /\.sort\(\(a,\s*b\)\s*=>\s*a\.time\s*-\s*b\.time/);

  const queueStart = page.indexOf('<section className="queue-section"');
  const queueEnd = page.indexOf("</section>", queueStart);
  const queue = page.slice(queueStart, queueEnd);
  assert.match(queue, /instanceQueueEntries\.map/);
  assert.match(queue, /selectInstanceQueueEntry/);
  assert.match(queue, /className="queue-arrow"[\s\S]*?Open details for/);
  assert.match(queue, /className="queue-confidence"[\s\S]*?<input type="number" min="0" max="100"[\s\S]*?value=\{entry\.confidence\}/);
  assert.match(queue, /updateQueueConfidence\(entry\.kind,\s*entry\.id,\s*Number\(event\.target\.value\)\)/);
  assert.ok(queue.indexOf('className="queue-confidence"') < queue.indexOf('className="queue-arrow"'), "confidence is immediately left of the details arrow");
  assert.match(queue, /setQueueDetailTarget\(\{ kind: entry\.kind, id: entry\.id \}\)/);
  assert.doesNotMatch(queue, /setCandidates|Manual review target|\+ Add/, "the queue is navigation-only");
});

test("edits queue confidence without a slider and synchronizes the annotation editor", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const updateStart = page.indexOf("const updateQueueConfidence");
  const updateEnd = page.indexOf("const deleteAnnotation", updateStart);
  const update = page.slice(updateStart, updateEnd);

  assert.match(update, /Math\.round\(clamp\(/);
  assert.match(update, /updateAnnotation\(id,\s*\{\s*confidence\s*\}\)/);
  assert.match(update, /setCandidates\(\(items\)\s*=>\s*items\.map/);
  assert.match(page, /confidence:\s*0/, "new imported file events begin explicitly unscored");
  assert.match(page, /confidence:\s*prior\.confidence/, "edited file-event confidence survives reimport");
  assert.match(page, /Number\.isFinite\(candidate\.uncertainty\)[\s\S]*?100\s*-\s*Number\(candidate\.uncertainty\)/, "legacy uncertainty values migrate to confidence");

  const queueStart = page.indexOf('<section className="queue-section"');
  const queueEnd = page.indexOf("</section>", queueStart);
  const queue = page.slice(queueStart, queueEnd);
  assert.doesNotMatch(queue, /type="range"/);
});

test("opens queue-item details with complete notes and context", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const modalStart = page.indexOf("{queueDetailEntry &&");
  const modalEnd = page.indexOf("{showAnnotationEditor", modalStart);
  const modal = page.slice(modalStart, modalEnd);

  assert.match(modal, /role="dialog"[^>]*aria-modal="true"/);
  assert.match(modal, /Close queue item details/);
  assert.match(modal, /TIMED CONTEXT/);
  assert.match(modal, /CONTEXT \/ NOTES/);
  assert.match(modal, /<span>Confidence<\/span><strong>\{queueDetailEntry\.confidence\}%<\/strong>/);
  assert.match(modal, /queueDetailAnnotation\?\.notes\?\.trim\(\)/);
  assert.match(modal, /CHANNEL PROVENANCE/);
  assert.match(modal, /Jump to location/);
  assert.match(modal, /Open annotation/);
});

test("does not tint the waveform for whole-session labels", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const canvasDrawStart = page.indexOf("const displayStart = viewStart");
  const drawStart = page.indexOf("for (const item of annotations)", canvasDrawStart);
  const drawEnd = page.indexOf("const traceOrder", drawStart);
  const shading = page.slice(drawStart, drawEnd);

  assert.match(shading, /const geometry = annotationGeometry\(item\)/);
  assert.match(shading, /if \(geometry === "session"\) continue/);
  assert.ok(
    shading.indexOf('if (geometry === "session") continue') < shading.indexOf("context.fillRect"),
    "whole-session labels are skipped before any annotation color is painted",
  );
});

test("defers signal-window loading until wheel panning settles", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const wheelStart = page.indexOf("const onViewerWheel");
  const wheelEnd = page.indexOf("useLayoutEffect", wheelStart);
  const wheel = page.slice(wheelStart, wheelEnd);
  const effectStart = page.lastIndexOf("useEffect(() => {", page.indexOf("const requestId = ++displayRequestIdRef.current"));
  const playbackGuard = page.indexOf("if (!hasRecording || !playing)", page.indexOf("const requestId = ++displayRequestIdRef.current"));
  const effectEnd = page.lastIndexOf("useEffect(() => {", playbackGuard);
  assert.ok(effectStart >= 0 && effectEnd > effectStart, "signal-window refresh effect is present");
  const effect = page.slice(effectStart, effectEnd);
  assert.match(wheel, /previewViewStartSafe\(/, "wheel frames update only the visible viewport");
  assert.match(wheel, /clearWheelPanSettle\(\)[\s\S]*?window\.setTimeout/, "continued wheel movement restarts the settle timer");
  assert.match(wheel, /setSignalViewStart\(wheelPanTargetRef\.current\)[\s\S]*?WHEEL_PAN_SETTLE_MS/, "the final position is committed after the gesture pauses");
  assert.match(effect, /requiredStart\s*=\s*Math\.max\(0, signalViewStart/, "signal reads use the settled position");
  assert.match(effect, /displayRefreshPendingRef\.current\s*=\s*refreshWindow/, "the settled request replaces any pending read");
  assert.match(effect, /pumpLatestWindow/, "the newest requested window is pumped without building a stale read backlog");
  assert.match(effect, /displayAppliedRequestIdRef/, "out-of-order reads cannot overwrite a newer rendered window");
  assert.match(page, /const displayStart = viewStart/, "the existing waveform moves continuously with the live viewport");
});

test("keeps whole-session context out of the timed tracks and preserves exact label geometry", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");

  assert.match(page, /const bottomAnnotations[\s\S]*?annotationGeometry\(item\)\s*!==\s*"session"/);
  assert.match(page, /bottomAnnotations\.filter\(\(item\)\s*=>\s*item\.track\s*===\s*track\.id\)/);
  assert.match(page, /\{ id: "context", label: "Context Labels" \}/);
  assert.match(page, /\{ id: "windowed", label: "ePhys Window Labels" \}/);
  assert.match(page, /\{ id: "instance", label: "ePhys Instance Labels" \}/);
  assert.match(page, /return geometry === "window" \? "interval" : geometry/, "legacy fixed windows migrate to ordinary movable intervals");
  assert.doesNotMatch(page, /id: "(?:wake|sleep-unspecified|n1|n2|n3|rem)"[^\n]+geometry: "window"/);

  const dragStart = page.indexOf("const applyPreview");
  const dragEnd = page.indexOf("const startAnnotationDrag", dragStart);
  const drag = page.slice(dragStart, dragEnd);
  assert.match(drag, /geometry\s*=\s*target\s*===\s*"instance"\s*\?\s*"point"\s*:\s*"interval"/);
  assert.doesNotMatch(drag, /geometry\s*=\s*"window"/);
});

test("gives wrapped bottom-track labels vertical breathing room", async () => {
  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  assert.match(css, /\.timeline-row\s*\{\s*height:\s*46px;\s*\}/);
  assert.match(css, /\.track-label\s*\{[^}]*padding-top:\s*5px;[^}]*padding-bottom:\s*5px;[^}]*line-height:\s*1\.35;/);
});

test("toggles the complete bottom label-track surface from the centered panel control", async () => {
  const [page, css] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);
  assert.match(page, /const \[bottomTracksOpen,\s*setBottomTracksOpen\]\s*=\s*useState\(true\)/);
  assert.match(page, /\{bottomTracksOpen && <div[\s\S]*?className=\{`timeline/);
  assert.match(page, /Hide" : "Show"\} bottom label tracks/);
  assert.match(css, /\.panel-toggle-pair\s*\{[^}]*position:\s*relative;[^}]*padding-bottom:\s*10px;/);
  assert.match(css, /\.panel-bottom-button\s*\{[^}]*position:\s*absolute;[^}]*left:\s*50%;[^}]*bottom:\s*0;/);
});

test("box-selects labels and moves or deletes the selected group atomically", async () => {
  const [page, css] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);

  assert.match(page, /const \[selectedAnnotationIds,\s*setSelectedAnnotationIds\]\s*=\s*useState<Set<string>>/);
  assert.match(page, /const \[annotationSelectionBox,\s*setAnnotationSelectionBox\]/);
  assert.match(page, /querySelectorAll<HTMLElement>\("\[data-annotation-id\]"\)/);
  assert.match(page, /const intersects\s*=\s*rect\.right\s*>=\s*leftClient[\s\S]*?rect\.top\s*<=\s*bottomClient/);
  assert.equal((page.match(/data-annotation-id=\{item\.id\}/g) ?? []).length, 2);
  assert.match(page, /selectedAnnotationIds\.has\(item\.id\)\s*\?\s*"selected"/);
  assert.match(page, /drag\.mode\s*===\s*"move"\s*&&\s*drag\.originals\.length\s*>\s*1/);
  assert.match(page, /const sharedDelta\s*=\s*clamp\(snappedDelta,\s*-earliest,\s*meta\.durationSec\s*-\s*latest\)/);
  assert.match(page, /Object\.fromEntries\(drag\.originals\.map/);
  assert.match(page, /if\s*\(selectedAnnotationIds\.size\)\s*moveSelectedAnnotations\(-1,\s*event\.shiftKey\)/);
  assert.match(page, /if\s*\(selectedAnnotationIds\.size\)\s*moveSelectedAnnotations\(1,\s*event\.shiftKey\)/);
  assert.match(page, /Delete"\s*\|\|\s*event\.key\s*===\s*"Backspace"\)\s*&&\s*selectedAnnotationIds\.size/);
  assert.match(page, /deleteSelectedAnnotations\(\)/);
  assert.match(page, /commitMutation\(\(\)\s*=>\s*remaining\)/);
  assert.match(css, /\.annotation-selection-box\s*\{[^}]*border:\s*1px dashed #7ce8c7;[^}]*pointer-events:\s*none;/);
});

test("highlights a focused channel and provides compact or vertically scrollable channel layouts", async () => {
  const [page, css] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);

  assert.match(page, /const focused = !inspectionDragging && !inspectionRange\?\.dragged && focusedChannel === index/);
  assert.match(page, /aria-pressed=\{focused\}/);
  assert.match(page, /setFocusedChannel\(index\)/);
  assert.match(page, /waveform-wrap \$\{expandedChannels \? "channel-scroll-mode" : ""\}/);
  assert.match(page, /--channel-content-height/);
  assert.match(page, /aria-pressed=\{expandedChannels \|\| Boolean\(waveformVerticalViewport\)\}/);
  assert.match(css, /\.waveform-wrap\.channel-scroll-mode[\s\S]*?height:\s*0[\s\S]*?overflow-y:\s*scroll/);
  assert.match(css, /\.waveform-wrap\.channel-scroll-mode \.canvas-column\s*\{\s*overflow:\s*visible/);
  assert.match(css, /\.channel-rail button\.focused/);
});

test("aligns waveform rows and pointer hit-testing with the channel rail", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  assert.match(page, /const CHANNEL_RAIL_HEADER_HEIGHT\s*=\s*28/);

  const drawStart = page.indexOf("const plotTop = CHANNEL_RAIL_HEADER_HEIGHT");
  const drawEnd = page.indexOf("if (markOnset !== null)", drawStart);
  const draw = page.slice(drawStart, drawEnd);
  assert.match(draw, /const plotTop\s*=\s*CHANNEL_RAIL_HEADER_HEIGHT/);
  assert.match(draw, /const plotHeight\s*=\s*expandedChannels[\s\S]*?Math\.max\(1,\s*height\s*-\s*plotTop\)/);
  assert.match(draw, /const verticalUnitStart\s*=\s*expandedChannels[\s\S]*?waveformVerticalViewport\?\.top/);
  assert.match(draw, /const verticalUnitSpan\s*=\s*expandedChannels[\s\S]*?waveformVerticalViewport\?\.bottom/);
  assert.match(draw, /const rowTopForChannel\s*=\s*\(channel: number\)\s*=>\s*plotTop[\s\S]*?channelRowLayout\.rowStartUnits\[channel\]\s*-\s*verticalUnitStart/);
  assert.match(draw, /const rowTop\s*=\s*rowTopForChannel\(channel\)/);
  assert.match(draw, /const center\s*=\s*rowTop\s*\+\s*rowHeight\s*\*\s*0\.5/);
  assert.match(draw, /context\.rect\(0,\s*rowTop,\s*width,\s*rowHeight\)[\s\S]*?context\.clip\(\)/, "each channel is clipped to its exact row without a minimum-height bleed");
  assert.ok((draw.match(/confineTraceYValueToRow\(/g) ?? []).length >= 2, "direct and raw reduction paths hard-limit trace coordinates to the row without allocating point objects");
  assert.match(page, /function drawOverviewEnvelope[\s\S]*?confineTraceYValueToRow/, "the connected overview envelope is confined by the same row boundary");
  assert.match(draw, /traceYOverflowsRow/, "overflow reporting remains separate from allocation-free coordinate confinement");
  assert.match(draw, /if\s*\(overflow\)[\s\S]*?context\.closePath\(\)/, "clipped excursions leave an overflow marker");
  assert.match(draw, /const markerHalfHeight\s*=\s*Math\.min\(4,\s*rowHeight\s*\*\s*\.4\)/, "overflow markers cannot leave compact channel rows");
  assert.match(draw, /if\s*\(rowHeight\s*>=\s*2\)[\s\S]*?context\.strokeRect/, "focused-row borders are omitted when a compact row is too short to contain the stroke");
  assert.match(page, /const ANATOMICAL_GROUP_GAP_ROWS\s*=\s*4/);
  assert.match(page, /const indices = orderAnatomicalChannelIndices\(meta\.channelLabels, selectedIndices\)/, "every recording uses anatomical channel ordering");
  assert.match(page, /channelRowFromFraction\(\s*channelRowLayout/);
  assert.match(draw, /robustTraceBaseline\(values\)[\s\S]*?max\s*-\s*baseline/, "each trace is centered on a robust display-window baseline");
  assert.match(draw, /if \(!Number\.isFinite\(value\)\)[\s\S]*?connected\s*=\s*false/, "non-finite source gaps break the drawn trace");
  assert.match(draw, /const traceOrder[\s\S]*?focusedChannel/, "the focused trace is drawn last for readability");
  assert.match(draw, /legacyRawCountDisplay[\s\S]*?LEGACY_RAW_COUNTS_PER_ROW/, "uncalibrated legacy DAT uses MATLAB's raw-count row spacing");
  assert.match(draw, /barValue\s*=\s*\(legacyRawCountDisplay\s*\?\s*5_000\s*:\s*100\)\s*\/\s*gain/, "the scale bar stays inside one row as gain changes");

  const hitStart = page.indexOf("const channelRowFromClientY");
  const hitEnd = page.indexOf("const timeFromPointer", hitStart);
  const hit = page.slice(hitStart, hitEnd);
  assert.match(hit, /liveScrollTop\s*\+\s*localY\s*-\s*CHANNEL_RAIL_HEADER_HEIGHT/);
  assert.match(hit, /channelRowLayout\.totalUnits\s*\*\s*60/);
  assert.match(hit, /rect\.height\s*-\s*CHANNEL_RAIL_HEADER_HEIGHT/);
  assert.match(page, /const row\s*=\s*channelRowFromClientY\(event\.clientY,\s*rect\)/);
});

test("renders wide recordings with a clipped-voltage halo around out-of-range peaks", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const overviewStart = page.indexOf("function drawOverviewEnvelope");
  const overviewEnd = page.indexOf("function expectedEDFRecordBytes", overviewStart);
  const overview = page.slice(overviewStart, overviewEnd);
  assert.match(overview, /context\.closePath\(\)[\s\S]*?context\.fill\(\)/, "extrema form a connected filled silhouette");
  assert.match(overview, /gaussianClippingHaloIntensity/);
  assert.match(overview, /clippingExcessIntensity/);
  assert.match(overview, /peakWidth/, "true exceedances remain narrow peaks over the Gaussian trail");
  assert.match(overview, /showClippingHalo\s*&&\s*rowHeight\s*>=\s*4/);
  assert.match(overview, /clippingThresholdMicrovolts\s*=\s*100[\s\S]*?fullColorExcessMicrovolts\s*=\s*200/);
  assert.match(overview, /context\.fillRect\(left,\s*ribbonTop/, "clipped peaks use a thin time-aligned indicator rather than vertical frequency strokes");

  const envelopeBranchStart = page.indexOf("if (envelope) {");
  const envelopeBranchEnd = page.indexOf("} else if (values.length", envelopeBranchStart);
  const envelopeBranch = page.slice(envelopeBranchStart, envelopeBranchEnd);
  assert.match(envelopeBranch, /drawOverviewEnvelope\(/);
  assert.match(envelopeBranch, /envelopeWindowMatchesViewport\([\s\S]*?envelope\.startSec[\s\S]*?envelope\.bucketDurationSec[\s\S]*?values\.length[\s\S]*?displayStart[\s\S]*?timebase/);
  assert.doesNotMatch(envelopeBranch, /drawContinuousTrace\(/, "bucket midpoints are not connected into a fake low-frequency waveform");
  assert.doesNotMatch(envelopeBranch, /context\.moveTo\(x,[\s\S]*?context\.lineTo\(x,/, "overview buckets are not rendered as a repetitive vertical comb");
  assert.match(page, /dark green → lime → yellow → orange marks distance beyond ±100 µV/);
  assert.match(page, /drawSampleClippingRibbon\([\s\S]*?values,[\s\S]*?values,/, "close raw-sample views retain the clipping ribbon");
  assert.match(page, /drawSampleClippingRibbon\([\s\S]*?minima,[\s\S]*?maxima,[\s\S]*?gaps,/, "pixel-envelope views retain the clipping ribbon");
});

test("filters padded signal data and crops back to the requested viewport", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const refreshStart = page.indexOf("const refreshWindow");
  const refreshEnd = page.indexOf("displayRefreshPendingRef.current = refreshWindow", refreshStart);
  const refresh = page.slice(refreshStart, refreshEnd);

  assert.match(refresh, /filterPadSec/);
  assert.match(refresh, /processingPadSec\s*=\s*filterPadSec\s*\+\s*groupDelayPadSec/);
  assert.match(refresh, /requiredStart\s*=\s*Math\.max\(0,\s*signalViewStart\s*-\s*processingPadSec\)/);
  assert.match(refresh, /requiredEnd\s*=\s*Math\.min\(meta\.durationSec,\s*signalViewStart\s*\+\s*timebase\s*\+\s*processingPadSec\)/);
  assert.match(refresh, /rawWindowCacheRef\.current\.find/, "adjacent pans reuse a bounded raw window cache");
  assert.match(refresh, /source\.getWindow\(\s*cacheStart/);
  assert.match(refresh, /processDisplaySignalsOffThread/, "clinical display preparation runs off-thread before the viewport crop");
  assert.match(refresh, /sourceStartSampleIndices/);
  assert.match(refresh, /cropStart[\s\S]*?channel\.subarray\(/, "filter settling samples are removed before rendering");
  assert.match(refresh, /requestId\s*!==\s*displayRequestIdRef\.current/, "stale processing work cannot overwrite the newest pan");
});

test("uses every available context lane before compressing overlapping labels", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  assert.match(page, /const contextLaneHeight\s*=\s*34/);
  assert.match(page, /Math\.floor\(\(contextTrackHeight\s*-\s*10\)\s*\/\s*contextLaneHeight\)/);
  assert.match(page, /contextLaneLayout\.laneCount\s*<=\s*contextLaneCapacity[\s\S]*?\?\s*contextLaneHeight/);
  assert.match(page, /clamp\(resize\.startHeight[\s\S]*?,\s*44,\s*420\)/, "the context surface can expand far enough for dense concurrent context");
});

test("renders the source-event review loop and event-relative candidate marks", async () => {
  const [page, css] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);

  assert.match(page, /activeCandidateItem/);
  assert.match(page, /SOURCE EVENT · 0\.000 s/);
  assert.match(page, /className="candidate-review-bar"/);
  assert.match(page, /Mark onset \/ offset/);
  assert.match(page, /Accept &amp; next/);
  assert.match(page, /skipActiveCandidate/);
  assert.match(page, /NA · Not rated/);
  assert.match(page, /formatRelativeTime\(activeCandidateOnset\s*-\s*activeCandidateItem\.time\)/);
  assert.match(css, /\.candidate-review-bar\s*\{/);
  assert.match(css, /\.candidate-relative-times\s*\{/);
});
